a=int(input("enter the number 1:"))
b=int(input("enter the number 2:"))
#print("sum of a and b is:",a+b)#addition operator
print("addition of a and b is:",a+b)
print("substraction of a and b is:",a-b)
print("Multiplication of a and b is:",a*b)
print("Division of a and b is:",a/b)
print("Modulus of a and b is:",a%b)
print("floor division of a and b is:",a//b)
print("Exponentiation of a and b is:",a**b)